export const playlistItemsMock = [
  {
    kind: 'youtube#playlistItem',
    etag: 'fWHuCFNJxy8BzmqYFzVKHsDSrUo',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS41MUY0NzFFRjMwMkI3RTI1',
    snippet: {
      publishedAt: '2022-03-04T08:36:10Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '夏ノ雪',
      description:
        'Provided to YouTube by NexTone Inc.\n\n夏ノ雪 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/6D4mOnSifzI/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/6D4mOnSifzI/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/6D4mOnSifzI/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/6D4mOnSifzI/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/6D4mOnSifzI/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 0,
      resourceId: {
        kind: 'youtube#video',
        videoId: '6D4mOnSifzI',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: '6D4mOnSifzI',
      videoPublishedAt: '2022-03-03T10:06:42Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'izBewZoIeH_XS4-H8IqSwC-Qa3Y',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS5DM0UwMkNDRTIwQUNDMjE2',
    snippet: {
      publishedAt: '2022-03-04T08:36:51Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '光ノ風吹ク丘',
      description:
        'Provided to YouTube by NexTone Inc.\n\n光ノ風吹ク丘 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/9XV7TeThdVA/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/9XV7TeThdVA/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/9XV7TeThdVA/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/9XV7TeThdVA/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/9XV7TeThdVA/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 1,
      resourceId: {
        kind: 'youtube#video',
        videoId: '9XV7TeThdVA',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: '9XV7TeThdVA',
      videoPublishedAt: '2022-03-03T10:01:14Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'p1aIZL275qCfXHcNDEybH5eUjjc',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS5FRjZBRjlFMTZFQkZCNzE5',
    snippet: {
      publishedAt: '2022-03-04T08:37:00Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '不完全ナ石',
      description:
        'Provided to YouTube by NexTone Inc.\n\n不完全ナ石 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/pJm3RsAbksw/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/pJm3RsAbksw/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/pJm3RsAbksw/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/pJm3RsAbksw/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/pJm3RsAbksw/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 2,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'pJm3RsAbksw',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'pJm3RsAbksw',
      videoPublishedAt: '2022-03-03T10:04:57Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'lyuKgw28jmaK2bwbbOIwjlqYyug',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS44MjZDNDYzQjgwQzkzQzkz',
    snippet: {
      publishedAt: '2022-03-04T08:37:07Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '青イ鳥',
      description:
        'Provided to YouTube by NexTone Inc.\n\n青イ鳥 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/TBYQ9_QrJZE/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/TBYQ9_QrJZE/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/TBYQ9_QrJZE/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/TBYQ9_QrJZE/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/TBYQ9_QrJZE/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 3,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'TBYQ9_QrJZE',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'TBYQ9_QrJZE',
      videoPublishedAt: '2022-03-03T10:02:10Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'WsCBmC2kj1i1KA-e2n_as7wL_6k',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS5FRDc0QkQxMzlEMTZBMzg0',
    snippet: {
      publishedAt: '2022-03-04T08:37:20Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '心閉ザセシ鉄棺',
      description:
        'Provided to YouTube by NexTone Inc.\n\n心閉ザセシ鉄棺 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/df4oPN2j4ig/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/df4oPN2j4ig/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/df4oPN2j4ig/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/df4oPN2j4ig/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/df4oPN2j4ig/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 4,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'df4oPN2j4ig',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'df4oPN2j4ig',
      videoPublishedAt: '2022-03-03T10:03:53Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'J87qrJGjLbMn0hx6wFGNgDeygsk',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS45REM1NzQ1MDM2OUZDNDMx',
    snippet: {
      publishedAt: '2022-03-04T08:37:28Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: 'オバアチャン',
      description:
        'Provided to YouTube by NexTone Inc.\n\nオバアチャン · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/f03IHCr9dJY/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/f03IHCr9dJY/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/f03IHCr9dJY/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/f03IHCr9dJY/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/f03IHCr9dJY/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 5,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'f03IHCr9dJY',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'f03IHCr9dJY',
      videoPublishedAt: '2022-03-03T10:03:27Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'LhBwfUwgnxauWrbIRyulUJMuJ1k',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS5DMTA0RkI2RTNGNUQ0Njgw',
    snippet: {
      publishedAt: '2022-03-04T08:37:35Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: 'イニシエノウタ/デボル',
      description:
        'Provided to YouTube by NexTone Inc.\n\nイニシエノウタ/デボル · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/mJPG2RxJ6RE/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/mJPG2RxJ6RE/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/mJPG2RxJ6RE/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/mJPG2RxJ6RE/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/mJPG2RxJ6RE/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 6,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'mJPG2RxJ6RE',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'mJPG2RxJ6RE',
      videoPublishedAt: '2022-03-03T10:06:03Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'Fg6V5ZDwOSRBfr5J4HAtsjE64E4',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS45NkM5QURGMTI1Rjg4NDRC',
    snippet: {
      publishedAt: '2022-03-04T08:37:44Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '愚カシイ機械',
      description:
        'Provided to YouTube by NexTone Inc.\n\n愚カシイ機械 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/NwlPsvXaLy8/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/NwlPsvXaLy8/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/NwlPsvXaLy8/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/NwlPsvXaLy8/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/NwlPsvXaLy8/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 7,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'NwlPsvXaLy8',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'NwlPsvXaLy8',
      videoPublishedAt: '2022-03-03T10:03:14Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'P9pZFupUcuSL4oyP9q_OudssYRE',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS5CMDU4Mjk2QjA2QTIwODZB',
    snippet: {
      publishedAt: '2022-03-04T08:37:52Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '売買ノ街',
      description:
        'Provided to YouTube by NexTone Inc.\n\n売買ノ街 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/cEvT_kPYQDI/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/cEvT_kPYQDI/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/cEvT_kPYQDI/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/cEvT_kPYQDI/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/cEvT_kPYQDI/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 8,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'cEvT_kPYQDI',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'cEvT_kPYQDI',
      videoPublishedAt: '2022-03-03T10:09:45Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'WuDzOJU7GAU15_OFdJWq5cV2bIY',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS44NEFDRUNBRDQwODFGNEU1',
    snippet: {
      publishedAt: '2022-03-04T08:37:59Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: 'イニシエノウタ/ポポル',
      description:
        'Provided to YouTube by NexTone Inc.\n\nイニシエノウタ/ポポル · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/UZBELmCNXUw/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/UZBELmCNXUw/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/UZBELmCNXUw/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/UZBELmCNXUw/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/UZBELmCNXUw/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 9,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'UZBELmCNXUw',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'UZBELmCNXUw',
      videoPublishedAt: '2022-03-03T10:07:12Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'xeojsgDk2HYx93ITsApXIQIfdTA',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS5CNTQ4NEJFQThFNzg4Q0Qz',
    snippet: {
      publishedAt: '2022-03-04T08:44:12Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '仮面ノ誉',
      description:
        'Provided to YouTube by NexTone Inc.\n\n仮面ノ誉 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/_ymjuIOeo8I/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/_ymjuIOeo8I/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/_ymjuIOeo8I/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/_ymjuIOeo8I/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/_ymjuIOeo8I/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 10,
      resourceId: {
        kind: 'youtube#video',
        videoId: '_ymjuIOeo8I',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: '_ymjuIOeo8I',
      videoPublishedAt: '2022-03-03T10:09:45Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'gcP53ek-Hkla7-EBziOH-Dxu8wc',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS40MzQwRDA4N0ZGRTNBNTE2',
    snippet: {
      publishedAt: '2022-03-04T08:44:20Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '流砂ノ神殿',
      description:
        'Provided to YouTube by NexTone Inc.\n\n流砂ノ神殿 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/C1ztL9-Ld4s/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/C1ztL9-Ld4s/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/C1ztL9-Ld4s/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/C1ztL9-Ld4s/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/C1ztL9-Ld4s/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 11,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'C1ztL9-Ld4s',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'C1ztL9-Ld4s',
      videoPublishedAt: '2022-03-03T10:08:28Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'vLNWKxBuHBnCI7lMjGWVH8IsayY',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS41QUU4MjI2RjNBNjFENEY3',
    snippet: {
      publishedAt: '2022-03-04T08:44:28Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '掟ニ囚ワレシ神',
      description:
        'Provided to YouTube by NexTone Inc.\n\n掟ニ囚ワレシ神 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/_NwYIkPiCus/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/_NwYIkPiCus/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/_NwYIkPiCus/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/_NwYIkPiCus/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/_NwYIkPiCus/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 12,
      resourceId: {
        kind: 'youtube#video',
        videoId: '_NwYIkPiCus',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: '_NwYIkPiCus',
      videoPublishedAt: '2022-03-03T10:06:28Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'Kdx0yuNyr3HcNN-PfSxA_A3mOUQ',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS4zREM4MEQ5NkI0RDExOEYy',
    snippet: {
      publishedAt: '2022-03-04T08:44:36Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '最終兵器',
      description:
        'Provided to YouTube by NexTone Inc.\n\n最終兵器 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/sW9kTkKEiEo/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/sW9kTkKEiEo/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/sW9kTkKEiEo/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/sW9kTkKEiEo/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/sW9kTkKEiEo/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 13,
      resourceId: {
        kind: 'youtube#video',
        videoId: 'sW9kTkKEiEo',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: 'sW9kTkKEiEo',
      videoPublishedAt: '2022-03-03T10:09:11Z',
    },
  },
  {
    kind: 'youtube#playlistItem',
    etag: 'fLNXMYmqaK8qTIRb2R-Rmvgbcbw',
    id: 'UExkUjdtN1BGTHpRNjQ0Vng2M1Y5cFdqOG84WWk3MHlCcS41RTFEM0JFNjc4MDNBMzA5',
    snippet: {
      publishedAt: '2022-03-04T08:44:46Z',
      channelId: 'UCeLKAEq98Qu3UuCobhSupSg',
      title: '深紅ノ敵',
      description:
        'Provided to YouTube by NexTone Inc.\n\n深紅ノ敵 · SQUARE ENIX MUSIC · Keiichi Okabe · MONACA\n\nNieR Gestalt & NieR Replicant Original Soundtrack\n\nReleased on: 2010-04-21\n\nAuto-generated by YouTube.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/2Vs1DxFK3f4/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/2Vs1DxFK3f4/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/2Vs1DxFK3f4/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/2Vs1DxFK3f4/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/2Vs1DxFK3f4/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'AsK_0',
      playlistId: 'PLdR7m7PFLzQ644Vx63V9pWj8o8Yi70yBq',
      position: 14,
      resourceId: {
        kind: 'youtube#video',
        videoId: '2Vs1DxFK3f4',
      },
      videoOwnerChannelTitle: 'SQUARE ENIX MUSIC - Topic',
      videoOwnerChannelId: 'UCP1gKdRIuuv23t4_UlnE6wA',
    },
    contentDetails: {
      videoId: '2Vs1DxFK3f4',
      videoPublishedAt: '2022-03-03T10:07:54Z',
    },
  },
];
